tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "zsh"
brew "antigen"
brew "aws-iam-authenticator"
brew "bat"
brew "deno"
brew "fd"
brew "fzf"
brew "gh"
brew "git-lfs"
brew "git"
brew "imagemagick"
brew "k9s"
brew "lsd"
brew "macos-trash"
brew "node"
brew "ripgrep"
brew "starship"
brew "tree"
brew "watchman"
brew "wifi-password"
brew "yarn"
brew "z"

cask "airtable"
cask "bettertouchtool"
cask "dash"
cask "discord"
cask "docker"
cask "fig"
cask "finicky"
cask "firefox"
cask "flipper"
cask "font-fira-code"
cask "font-sauce-code-pro-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "mattermost"
cask "microsoft-edge"
cask "monitorcontrol"
cask "nordvpn"
cask "notion"
cask "obsidian"
cask "parallels"
cask "pocket-casts"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "raindropio"
cask "raycast"
cask "setapp"
cask "slack"
cask "spotify"
cask "swiftformat-for-xcode"
cask "temurin8"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "vlc"

mas "Magnet", id: 441258766
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 1147396723
mas "Telegram", id: 747648890
mas "Termius", id: 1176074088